font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 12.0

background #0a0a0a
foreground #e6e6e6

cursor #d61406
cursor_text_color background
cursor_shape beam
cursor_beam_thickness 1.8
cursor_blink_interval 0.6 cubic-bezier(0.4,0,0.2,1)
cursor_stop_blinking_after 10.0
cursor_trail 5
cursor_trail_decay 0.1 0.3

scrollbar_hover_width 0.7
scrollbar_radius 0.5
scrollbar_gap 0.5
scrollbar_track_hover_opacity 0
scrollbar_handle_color #d61406

default_pointer_shape arrow

selection_background #d61406
selection_foreground #ffffff

window_padding_width 15

confirm_os_window_close 0

tab_bar_edge bottom
tab_bar_style custom
active_tab_font_style normal
inactive_tab_font_style normal
tab_bar_margin_width 7.0
tab_bar_margin_height 7.0 7.0
tab_bar_align center
tab_separator " "
tab_title_template "{fmt.bg.default}{fmt.fg._6E6E6E}  {sup.index} 󰓩 {title}{bell_symbol}{activity_symbol}  {fmt.fg.default}"
active_tab_title_template "{fmt.bg.default}{fmt.fg._d61406}{fmt.bg._d61406}{fmt.fg._3A3A3A} {sup.index} 󰓩 {title}{bell_symbol}{activity_symbol} {fmt.bg.default}{fmt.fg._d61406}{fmt.bg.default}{fmt.fg.default}"
tab_bar_background #121212
active_tab_foreground #121212
inactive_tab_background #121212

shell_integration enabled
