general {
    ignore_empty_input = false
    hide_cursor = true
}

#Wallpaper
background {
    monitor = eDP-1
    path = ~/.config/hypr/Wallpaper.jpg
    color = rgb(214, 20, 6)
    blur_passes = 2
    blur_size = 3
}

#lockicon
image {
    window = eDP-1
    path = ~/.config/hypr/lock-icon.png
    border_size = 0
    size = 40
    position = 0, 315
}
#loginbox
shape { 
    monitor = eDP-1
    size = 350, 250
    color = rgba(0,0,0,0.6)
    rounding = 15

    position = -125, -158
    zindex = 0
}
#login header
label {
    monitor = eDP-1
    text = LOG IN
    font_size = 48
    font_family = CF Samurai Bob
    color = rgba(254, 254, 254, 0.6)

    position = -205, -73
    zindex = 1
}

#fake textebox for username
shape {
    monitor = eDP-1
    size = 300, 60
    color = rgba(0,0,0,0.7)

    rounding = 12
    position = -125, -158
    zindex = 1
}

# #username label
# label {
#     monitor = eDP-1
#     text = USERNAME
#     font_size = 8
#     color = rgb(204, 53, 53)

#     position = -240, -120
#     zindex = 2
# }

#username
label {
    monitor = eDP-1
    text = $DESC
    font_size = 14
    color = rgb(97, 97, 97)

    position = -193, -158
    zindex = 2
}

#password-field
input-field {
    monitor = eDP-1
    size = 300, 60
    outline_thickness = 2

    dots_size = 0.2
    dots_spacing = 0.3
    dots_center = false
    
    outer_color = rgb(0, 0, 0, 0)
    inner_color = rgba(0,0,0,0.7)
    font_color = rgb(97, 97, 97)

    placeholder_text = 
    fade_on_empty = false

    rounding = 12

    check_color = rgb(97, 97, 97)
    fail_color = rgb(255, 0, 0)
    fail_text = LEAVE ME ALONE
    
    position = -125, -228
    zindex = 1
}

#clock box
shape { 
    monitor = eDP-1
    size = 600, 300
    color = rgba(0,0,0,0.6)
    rounding = 15

    position = 0, 133
    zindex = 0
}

#Clock
label {
    monitor = eDP-1
    text = $TIME
    font_size = 120
    font_family = The Last Shuriken
    color = rgba(254, 254, 254, 0.6)

    position = 0, 150
    zindex = 1
}

#Week day
label {
    monitor = eDP-1
    text = cmd[update:3600000] date +"%A" 
    font_size = 60
    font_family = CF Samurai Bob
    color = rgba(254, 254, 254, 0.2)

    halign = left
    position = 710, 50
    zindex = 1
}

#date
label {
    monitor = eDP-1
    text = cmd[update:3600000] date +"%d, %b"
    font_size = 40
    font_family = CF Samurai Bob
    color = rgba(254, 254, 254, 0.2)

    halign = right
    position = -710, 48
    zindex = 1
}

#stats box
shape {
    monitor = eDP-1
    size = 234,250
    color = rgba(0,0,0,0.6)
    rounding = 15

    position = 183, -158
    zindex = 0
}

image {
    monitor = eDP-1
    path = ~/.config/hypr/widget.png
    size = 234
    border_size = 0

    position = 183, -158
    zindex = 1
}
