# This config is a STUB! This should never be generated.
# Use the default lua config from https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.lua

source = ./settings.conf
source = ./powersaveFlag.conf
source = ./monitors.conf
source = ./keybindings.conf
# source = ./windowrules.conf
source = ./animations.conf
source = ./gestures.conf
 
exec-once = swaync
exec-once = hyprpaper
exec-once = waybar
exec-once = hypridle
exec-once = hyprpolkitagent

exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = rm -rf ~/.local/share/cliphist/*

exec-once = hyprctl setcursor Bibata-Modern-Classic 24

env = QT_QPA_PLATFORMTHEME,qt6ct
env = GTK_THEME,Adwaita:dark

input {
    touchpad {
        natural_scroll = true
    }
}
