general {
    gaps_in = 6
    gaps_out = 12
    border_size = 2
    col.active_border = rgb(d61406)
    col.inactive_border = rgb(2a2a2a)
}

decoration {
    active_opacity = 0.8
    inactive_opacity = 0.7
    rounding = 15
    blur {
        enabled = true
        size = 7
        passes = 3
        xray = false
    }
}

layerrule = blur on, ignore_alpha 0, blur_popups on, match:namespace waybar
layerrule = blur on, ignore_alpha 0, xray 0, dim_around on, animation slidefade right 90%, match:namespace swaync-control-center
layerrule = blur on, ignore_alpha 0, xray 0, match:namespace swaync-notification-window
layerrule = blur on, ignore_alpha 0, xray 0, dim_around on, animation popin center, match:namespace rofi
