# hyprlang if WINDOWRULES_HYPRLAND_V_0_53

# idle_inhibit rules
windowrule = idle_inhibit fullscreen, match:class ^(.*celluloid.*)$|^(.*mpv.*)$|^(.*vlc.*)$
windowrule = idle_inhibit fullscreen, match:class ^(.*[Ss]potify.*)$
windowrule = idle_inhibit fullscreen, match:class ^(.*LibreWolf.*)$|^(.*floorp.*)$|^(.*brave-browser.*)$|^(.*firefox.*)$|^(.*chromium.*)$|^(.*zen.*)$|^(.*vivaldi.*)$


windowrule = opacity 0.90 $& 0.90 $& 1,match:class ^(firefox)$
windowrule = opacity 0.90 $& 0.90 $& 1,match:class ^(zen)$
windowrule = opacity 0.80 $& 0.80 $& 1,match:class ^([Cc]ode)$
windowrule = opacity 0.80 $& 0.80 $& 1,match:class ^(code-url-handler)$
windowrule = opacity 0.80 $& 0.80 $& 1,match:class ^(code-insiders-url-handler)$
windowrule = opacity 0.80 $& 0.80 $& 1,match:class ^(kitty)$
#windowrule = opacity 0.80 $& 0.80 $& 1,match:class ^(org.kde.dolphin)$
windowrule = opacity 0.80 $& 0.80 $& 1,match:class ^(qt5ct)$
windowrule = opacity 0.80 $& 0.80 $& 1,match:class ^(qt6ct)$
#windowrule = opacity 0.80 $& 0.80 $& 1,match:class ^(kvantummanager)$
windowrule = opacity 0.80 $& 0.70 $& 1,match:class ^(org.pulseaudio.pavucontrol)$
windowrule = opacity 0.80 $& 0.70 $& 1,match:class ^(nm-applet)$
windowrule = opacity 0.80 $& 0.70 $& 1,match:class ^(nm-connection-editor)$
windowrule = opacity 0.80 $& 0.70 $& 1,match:class ^(hyprpolkitagent)$
windowrule = opacity 0.80 $& 0.70 $& 1,match:class ^(org.freedesktop.impl.portal.desktop.gtk)$
windowrule = opacity 0.80 $& 0.70 $& 1,match:class ^(org.freedesktop.impl.portal.desktop.hyprland)$
windowrule = opacity 0.70 $& 0.70 $& 1,match:class ^([Ss]team)$
windowrule = opacity 0.70 $& 0.70 $& 1,match:class ^(steamwebhelper)$
windowrule = opacity 0.70 $& 0.70 $& 1,match:class ^([Ss]potify)$
windowrule = opacity 0.70 $& 0.70 $& 1,match:initial_title ^(Spotify Free)$
windowrule = opacity 0.70 $& 0.70 $& 1,match:initial_title ^(Spotify Premium)$

windowrule = opacity 0.80 0.80,match:class ^(discord)$ # Discord-Electron


layerrule = blur true,match:namespace rofi
layerrule = ignore_alpha 0,match:namespace rofi
layerrule = blur true,match:namespace notifications
layerrule = ignore_alpha 0,match:namespace notifications
layerrule = blur true,match:namespace swaync-notification-window
layerrule = ignore_alpha 0,match:namespace swaync-notification-window
layerrule = blur true,match:namespace swaync-control-center
layerrule = ignore_alpha 0,match:namespace swaync-control-center
layerrule = blur true,match:namespace logout_dialog

# hyprlang endif
